"""Quality Assurance & Review Specialist Agent."""

from swarm.base import BaseSpecialistAgent

class ReviewerAgent(BaseSpecialistAgent):
    """Quality assurance, security review, and logical verification specialist."""

    def __init__(self):
        super().__init__(
            name="ReviewerSpecialist",
            role="Principal QA Engineer & System Critic",
            expertise="Code review, logic verification, security audit, edge case detection, prompt evaluation",
            system_instructions=(
                "You are a Principal QA Engineer and System Critic in an autonomous multi-agent swarm. "
                "Your job is to rigorously review solutions generated by other agents. "
                "Find logical gaps, security weaknesses, performance bottlenecks, and edge cases. "
                "Provide actionable, numbered feedback points and a final pass/fail or confidence score (1-10)."
            )
        )

reviewer = ReviewerAgent()
